// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockAPI.Data;

#nullable disable

namespace StockAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StockAPI.Models.HistoricoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_movimento");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observacoes");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("int")
                        .HasColumnName("stock_anterior");

                    b.Property<int>("StockAtual")
                        .HasColumnType("int")
                        .HasColumnName("stock_atual");

                    b.Property<int>("TipoMovimento")
                        .HasColumnType("int")
                        .HasColumnName("tipo_movimento");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DataMovimento");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UserId");

                    b.ToTable("historico_stock");
                });

            modelBuilder.Entity("StockAPI.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_barras");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("imagem_url");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int")
                        .HasColumnName("stock_minimo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.ToTable("produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Categoria = "Fixação",
                            CodigoBarras = "5601234567890",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Parafuso de aço zincado M8x50mm",
                            Localizacao = "Corredor A - Prateleira 1",
                            Nome = "Parafuso M8x50",
                            PrecoUnitario = 0.15m,
                            Stock = 500,
                            StockMinimo = 100,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Categoria = "Fixação",
                            CodigoBarras = "5609876543210",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Porca sextavada M8 em aço zincado",
                            Localizacao = "Corredor A - Prateleira 1",
                            Nome = "Porca M8",
                            PrecoUnitario = 0.08m,
                            Stock = 450,
                            StockMinimo = 100,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Categoria = "Ferramentas",
                            CodigoBarras = "5605555555555",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chave de fendas Phillips tamanho PH2, cabo ergonómico",
                            Localizacao = "Corredor B - Prateleira 3",
                            Nome = "Chave de Fendas Phillips PH2",
                            PrecoUnitario = 4.99m,
                            Stock = 25,
                            StockMinimo = 10,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Categoria = "Elétrico",
                            CodigoBarras = "5601111111111",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Fita isoladora elétrica 19mm x 20m",
                            Localizacao = "Corredor C - Prateleira 2",
                            Nome = "Fita Isoladora Preta",
                            PrecoUnitario = 1.50m,
                            Stock = 80,
                            StockMinimo = 20,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Categoria = "Elétrico",
                            CodigoBarras = "5602222222222",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Cabo elétrico H07V-U 2.5mm² azul (por metro)",
                            Localizacao = "Corredor C - Prateleira 1",
                            Nome = "Cabo Elétrico 2.5mm²",
                            PrecoUnitario = 0.85m,
                            Stock = 5,
                            StockMinimo = 50,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StockAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_verified");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("verification_code");

                    b.Property<DateTime?>("VerificationCodeExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("verification_code_expiry");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@stockapi.pt",
                            IsVerified = true,
                            Nome = "Administrador",
                            PasswordHash = "$2a$11$K5HHjCKMk5F0z5e5o4KVPq.RjS5YLqJqKHFQK7qKPZ5K5K5K5K5K5",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StockAPI.Models.HistoricoStock", b =>
                {
                    b.HasOne("StockAPI.Models.Produto", "Produto")
                        .WithMany("Historico")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockAPI.Models.User", "User")
                        .WithMany("HistoricoMovimentos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockAPI.Models.Produto", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("StockAPI.Models.User", b =>
                {
                    b.Navigation("HistoricoMovimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
